#!/usr/bin/env bash
# Author: Aaron Caffrey
# Like the rest of screenfetch-c, this file is licensed under the MIT license.

# ./bootstrap && ./configure --prefix=/usr && make
# sudo make install

prog_name='screenfetch2'
prog_ver='1.4.0'


# configure.ac
configure_ac=("# This file is processed by autoconf to create a configure script
AC_INIT(["${prog_name}"], ["${prog_ver}"])
AC_CONFIG_AUX_DIR([temp_dir])
AM_CONFIG_HEADER(src/config.h)
AC_CONFIG_MACRO_DIR([m4])
AM_INIT_AUTOMAKE([1.11 -Wall no-define foreign subdir-objects dist-xz no-dist-gzip std-options])

AM_SILENT_RULES([yes])
AC_PROG_CC_STDC
AC_EXEEXT
AC_C_CONST
AC_HEADER_STDC
AM_PROG_CC_C_O

IT_PROG_INTLTOOL([0.40.0])
AM_GLIB_GNU_GETTEXT

GETTEXT_PACKAGE="${prog_name}"
AC_SUBST(GETTEXT_PACKAGE)

AC_CHECK_HEADERS(stdio.h stdlib.h stdbool.h \\
string.h unistd.h time.h ctype.h regex.h argp.h \\
sys/utsname.h inttypes.h malloc.h)

AC_DEFINE_UNQUOTED(GETTEXT_PACKAGE, "\"${prog_name}\"", [Gettext package.])
AC_DEFINE_UNQUOTED(PROG_VERSION, "\"${prog_ver}\"", [The current version])

# The linker flags tests in m4 dir
TEST_X11
TEST_OPENGL
TEST_JPEG

rm -f po/LINGUAS
for po_file in \`ls --color=never po/*.po | sort\`; do 
  echo \$po_file | awk -F '.' '{gsub(\"po/\",\"\");print \$1}' >> po/LINGUAS
done

AC_CONFIG_FILES([
Makefile
src/Makefile
src/scripts/Makefile
po/Makefile.in
])

AC_OUTPUT

echo
echo 'Now type \"make\" and \"sudo make install\" afterwards'
echo")


# Makefile.am
main_makefile=('
SUBDIRS = \
    src   \
    po    \
    src/scripts

man_MANS = \
    screenfetch-c.1
')


mac_win_cppflagz=''
mac_ldflagz=''
if type -p uname > /dev/null 2>&1; then
  uname_test=`uname -s`
  if test "$uname_test" = "Linux"; then
    plat_module='plat/linux/detect.c'

  elif test "$uname_test" = "Darwin"; then
    plat_module='plat/darwin/detect.c'
    mac_win_cppflagz='-D_DARWIN_C_SOURCE -D_DARWIN_USE_64_BIT_INODE'
    mac_ldflagz='-framework CoreServices'

  elif test "$uname_test" = "SunOS"; then
    plat_module='plat/sun/detect.c'
  fi
fi

# I guarantee that `machine' exists in OpenBSD
# We don't want to rely on `uname' only
if type -p machine > /dev/null 2>&1; then
  plat_module='plat/bsd/detect.c'
fi
# src/Makefile.am
src_files=(`ls --color=never src/*.{c,h} | awk '{gsub("src/","");print}'`)
src_makefile=('AM_CPPFLAGS = \
    -DLOCALEDIR=\"$(datadir)/locale\" \
    -D_POSIX_C_SOURCE=200112L '${mac_win_cppflagz}'

bin_PROGRAMS = \
    '${prog_name}'

'${prog_name}'_CFLAGS = \
    -O3 -std=c99 -Wall \
    -Wformat -Wunused-variable \
    -pedantic

'${prog_name}'_LDADD = $(X_LIBS) $(GL_LIBS) $(JPEG_LIBS) '${mac_ldflagz}'

'${prog_name}'_SOURCES = '${src_files[@]} 
 ${plat_module}' plat/common.c
')


# src/scripts/Makefile.am
src_scripts_makefile=('
bin_SCRIPTS = \
'`ls --color=never src/scripts`'
')


cat <<EOF > configure.ac
${configure_ac[@]}
EOF

cat <<EOF > Makefile.am
${main_makefile[@]}
EOF

cat <<EOF > src/Makefile.am
${src_makefile[@]}
EOF

cat <<EOF > src/scripts/Makefile.am
${src_scripts_makefile[@]}
EOF


# Add all modules that will be translated
# \nsrc/module_name.c
printf '%b' 'src/main.c\nsrc/parser.c\nsrc/disp.c\nsrc/plat/common.c' > 'po/POTFILES.in'


#screenfetch-c.1
man_page=(".\\\" Manpage for screenfetch-c
.\\\" Contact woodruffw on GitHub or at william @ tuffbizz.com to report any bugs or errors
.TH screenfetch-c 1 \"04 August 2013\" \""${prog_ver}"r\" \"User Commands\"
.SH NAME
.BR screenfetch-c \" - Display computer information and an ASCII logo\"
.SH SYNOPSIS
.B screenfetch-c
.RI [ OPTIONS ]
.SH DESCRIPTION
.B screenfetch-c
is a C rewrite of the original screenFetch, which was written in bash by Brett Bohnenkamper. 
Like the original, it displays both an ASCII logo determined by the computer's OS and a variety of statistics, including kernel type, ram, uptime, and so forth.
.SH COMPATIBILITY
Supported OSes:
Microsoft Windows, Mac OS X, FreeBSD, OpenBSD, NetBSD, DragonFlyBSD, Solaris and its derivatives, 
and most Linux-kernel based distributions.
.PP
.I Note:
If you are using manual mode to provide
.B screenfetch-c
with system information, you will need to enter the distribution name EXACTLY as written below:
Arch Linux, ParabolaGNU/Linux-libre, Chakra, Manjaro, Frugalware, Ubuntu, LinuxMint, SolusOS, Debian, LMDE, CrunchBang, Peppermint, LinuxDeepin, Trisquel, elementary OS, Backtrack Linux, Slackware, Gentoo, Sabayon, Funtoo, Fuduntu, Fedora, OpenSUSE, Red Hat Linux, Mandriva, Mandrake, Mageia, Viperr, Andoid, Linux, Solaris, Angstrom.
.PP
Supported shells:
GNU bash, csh, zsh, ksh, fish, dash, ash.
.SH OPTIONS
.PP
.BR \-v ,
.B \-\-verbose
.PP
Enable verbose mode, which prints out detection information.
.PP
.BR \-s ,
.B \-\-screenshot
.PP
Take a screenshot after completing the output.
On non\-Windows systems, this will save a file titled
.RI ' screenfetch_screenshot.png '
in
.BR $HOME .
On Windows, this will save the screenshot in the system clipboard.
.PP
.BR \-n ,
.B \-\-no-logo
.PP
Strip output of ASCII logo - print information only.
.PP
.BR \-D ,
.BI \-\-distro \" DISTRO\"
.PP
Set the distro outputted by
.BR screenfetch-c .
.PP
.BR \-E ,
.B \-\-suppress-errors
.PP
Suppress (most) error messages as they arise.
.PP
.BR \-p ,
.B \-\-portrait
.PP
Print output in portrait mode.
.PP
.BR \-V ,
.B \-\-version
.PP
Display the version of
.B screenfetch-c
currently being used.
.PP
.BR \-h ,
.B \-\-help
.PP
Displays help and compatibility information.
.PP
.BR \-L ,
.BI \-\-logo-only \" DISTRO\"
.PP
Output only the ASCII logo associated with that distro. Follows the general naming conventions of the
.B \-D
flag, but with \"OS X\", \"Windows\", and \"Solaris\" as possibilities as well.
.SH CONFIGURATION
When
.B screenfetch-c
is invoked with the
.B \-m
flag for the first time, it enters manual mode.
Manual mode prompts the user to enter specific information about the computer, storing that information in
.RI ~/ .screenfetchc
for the next invocation with the
.B \-m
flag.
.PP
By default, you must enter all fields asked for in manual mode. However, if you want
.B screenfetch-c
to skip a particular field while reading from the file, enter an asterisk (\"*\") for that section.
This will force
.B screenfetch-c
to attempt to detect that section, which may come in handy if you want to use manual mode for some sections but not for others.
.PP
To remove your existing manual configuration, simply delete the
.I .screenfetchc
file located in your
.BR $HOME . 
.PP
Note:
.IR .screenfetchc 's
format isn't exactly human-friendly, so editing it manually is
.B NOT
recommended.
.SH ENVIRONMENT
.B screenfetch-c
uses the following environment variables:
.PP
.BR USER \" - Used on BSD to determine the current user.\"
.PP
.BR HOME \" - Used to determine the user's home directory.\"
.PP
.BR SHELL \" - Used to determine the active shell.\"
.PP
Each of these variables must be defined properly in order for
.B screenfetch-c
to function as intended.
.SH RELEASE HISTORY
.IR 0.1 \" - ALPHA - INCOMPLETE, UNCOMPILED\"
.PP
.IR 0.5 \" - ALPHA - INCOMPLETE, TEST COMPILED\"
.PP
.IR 1.0 \" - BETA - LACKING MINOR PARTS, STABLE, WORKING ON MOST SYSTEMS\"
.PP
.IR 1.1 \" - BETA - NEARLY COMPLETE, MINOR BUGS AND GPU DETECTION NOT FINISHED\"
.PP
.IR 1.2 \" - RELEASE - WORKS ON THE MAJORITY OF SYSTEMS\"
.PP
.IR 1.3 \" - RELEASE - SIGNIFICANT REFACTORING AND PERFORMANCE IMPROVEMENTS\"
.PP
.IR 1.4 \" - RELEASE - CODE REDUCTION, PERFORMANCE IMPROVEMENTS AND NATIVIZATION ON LINUX\"
.SH BUGS AND ERRATIC BEHAVIOR
Shell version detection relies of very specific naming schemes and may appear incorrectly if any shell changes its versioning scheme.
.PP
DragonFly BSD systems with more than 4GiB of RAM may have their RAM stats displayed incorrectly, as 32-bit integers are used in sysctl.
.PP
Manual mode on Windows seems the result in a variety of weird bugs concerning uptime, packages, disk stats, and memory stats. For the time being, I recommend NOT using it on Windows.
.PP
Memory detection on Linux systems includes swap/buffer RAM in used RAM, not free RAM. While this is not a bug per se, it may contradict figures from other utilities (which factor out swap/buffer RAM).
.PP
Found a bug or issue? Please tell me about it:
.I http://github.com/woodruffw/screenfetch-c
.SH DIAGNOSTICS
.B screenfetch-c
has two built-in output modes: verbose (disabled by default) and error (enabled by default).
If a serious or fatal error occurs, the user will be notified via error (stderr).
Otherwise, the user may choose to enable the verbose mode, which display real-time detection.
.SH EXIT STATUS
.B screenfetch-c
returns
.B EXIT_SUCCESS
in all circumstances except for malformed argument strings.
For example,
.B screenfetch-c
will return
.B EXIT_FAILURE
if flagged with
.B \-D
but not given an additional argument.
.SH AUTHOR
.B screenfetch-c
was written and is maintained by William Woodruff
.RI ( \"william @ tuffbizz.com\" )
.PP
The original screenFetch was written by Brett Bohnenkamper
.RI ( \"kittykatt @ archlinux.us\" )
.PP
For a list of contributors to
.BR screenfetch-c ,
please refer to the CONTRIBUTORS file.
.SH SEE ALSO
.BR screenFetch (1)")

cat <<EOF > screenfetch-c.1
${man_page[@]}
EOF


# convert the man page to human readable text
# so we can gzip it later (if needed)
#if type -p groff > /dev/null 2>&1 && \
#   type -p col   > /dev/null 2>&1 && \
#   type -p uniq  > /dev/null 2>&1 && \
#   type -p mv    > /dev/null 2>&1; then

#  groff -man -Tascii screenfetch-c.1 | col -b | uniq > scr.1
#  mv scr.1 screenfetch-c.1

#fi



# do not remove nor edit
autoreconf --install --force